[package]
name = "foxglove"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.3.0"
chumsky = "1.0.0-alpha.4"
clap = { version = "4.4.2", features = ["derive"] }
cranelift = "0.99.1"
rustc-hash = "1.1.0"
